---
version: 2
jobs:
  build:
    working_directory: ~/northcenter-coupons
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: localhost
          PGUSER: northcenter-coupons
          RAILS_ENV: test
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: northcenter-coupons
          POSTGRES_DB: northcenter-coupons_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - type: cache-restore
        name: Restore bundle cache
        key: northcenter-coupons-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - type: cache-save
        name: Store bundle cache
        key: northcenter-coupons-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: DB Setup
          command: |
            cp config/database.yml.ci config/database.yml
            bin/rails db:schema:load

      - run: bundle exec rubocop

      - run: bundle exec rspec
